// This file is generated by scripts/generateFormatInstructions.ts
export const actionPlanCreateSpreadsheetFormatInstruction = (title: string): string => {
  return `{
      "type": 'createSpreadsheet',
      "title": string:${title},
    }`
}
