// This file is generated by scripts/generateFormatInstructions.ts
export const actionPlanCollectDataFormatInstruction = (name: string, url: string, description: string): string => {
  return `{
      "type": 'collectData',
      "name": string:${name},
      "url": string:${url},
      "description": string:${description},
    }`
}
