// This file is generated by scripts/generateFormatInstructions.ts
export const actionPlanCollectDataFormatInstruction = (name: string, webPageUrl: string, description: string): string => {
  return `{
      "type": 'collectData',
      "name": string:${name},
      "webPageUrl": string:${webPageUrl},
      "description": string:${description},
    }`
}
