// This file is generated by scripts/generateFormatInstructions.ts
export const spreadsheetSheetFormatInstruction = (sheetNumber: string, name: string, description: string): string => {
  return `{
      
      "sheetNumber": number:${sheetNumber},
      "name": string:${name},
      "description": string:${description},
    }`
}
