// This file is generated by scripts/generateFormatInstructions.ts
export const spreadsheetFormatInstruction = (name: string, description: string): string => {
  return `{
      
      "name": string:${name},
      "description": string:${description},
    }`
}
