// This file is generated by scripts/generateFormatInstructions.ts
export const webPageElementFormatInstruction = (top: string, left: string, width: string, height: string): string => {
  return `{
      "type": 'pageLink' | 'text' | null,
      "top": number:${top},
      "left": number:${left},
      "width": number:${width},
      "height": number:${height},
    }`
}
