// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPage } from '../../../../entities/WebPage'
import { checkEntityTypeWebPage } from '../single/checkEntityTypeWebPage'

export const checkEntityTypeWebPageList = (entity: unknown): entity is WebPage[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeWebPage(el)) {
      return false
    }
  }

  return true
}
