// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultAppendSheetToSpreadsheet } from '../../../../entities/ActionResultAppendSheetToSpreadsheet'
import { checkEntityTypeActionResultAppendSheetToSpreadsheet } from '../single/checkEntityTypeActionResultAppendSheetToSpreadsheet'

export const checkEntityTypeActionResultAppendSheetToSpreadsheetList = (entity: unknown): entity is ActionResultAppendSheetToSpreadsheet[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultAppendSheetToSpreadsheet(el)) {
      return false
    }
  }

  return true
}
