// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultReportResult } from '../../../../entities/ActionResultReportResult'
import { checkEntityTypeActionResultReportResult } from '../single/checkEntityTypeActionResultReportResult'

export const checkEntityTypeActionResultReportResultList = (entity: unknown): entity is ActionResultReportResult[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultReportResult(el)) {
      return false
    }
  }

  return true
}
