// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResult } from '../../../../entities/ActionResult'
import { checkEntityTypeActionResult } from '../single/checkEntityTypeActionResult'

export const checkEntityTypeActionResultList = (entity: unknown): entity is ActionResult[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResult(el)) {
      return false
    }
  }

  return true
}
