// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanReportResult } from '../../../../entities/ActionPlanReportResult'
import { checkEntityTypeActionPlanReportResult } from '../single/checkEntityTypeActionPlanReportResult'

export const checkEntityTypeActionPlanReportResultList = (entity: unknown): entity is ActionPlanReportResult[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanReportResult(el)) {
      return false
    }
  }

  return true
}
