// This file is generated by scripts/generateCheckEntityTypes.ts
import { CollectedData } from '../../../../entities/CollectedData'
import { checkEntityTypeCollectedData } from '../single/checkEntityTypeCollectedData'

export const checkEntityTypeCollectedDataList = (entity: unknown): entity is CollectedData[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeCollectedData(el)) {
      return false
    }
  }

  return true
}
