// This file is generated by scripts/generateCheckEntityTypes.ts
import { UserRequest } from '../../../../entities/UserRequest'
import { checkEntityTypeUserRequest } from '../single/checkEntityTypeUserRequest'

export const checkEntityTypeUserRequestList = (entity: unknown): entity is UserRequest[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeUserRequest(el)) {
      return false
    }
  }

  return true
}
