// This file is generated by scripts/generateCheckEntityTypes.ts
import { SpreadsheetSheet } from '../../../../entities/SpreadsheetSheet'
import { checkEntityTypeSpreadsheetSheet } from '../single/checkEntityTypeSpreadsheetSheet'

export const checkEntityTypeSpreadsheetSheetList = (entity: unknown): entity is SpreadsheetSheet[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeSpreadsheetSheet(el)) {
      return false
    }
  }

  return true
}
