// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanCreateSpreadsheet } from '../../../../entities/ActionPlanCreateSpreadsheet'
import { checkEntityTypeActionPlanCreateSpreadsheet } from '../single/checkEntityTypeActionPlanCreateSpreadsheet'

export const checkEntityTypeActionPlanCreateSpreadsheetList = (entity: unknown): entity is ActionPlanCreateSpreadsheet[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanCreateSpreadsheet(el)) {
      return false
    }
  }

  return true
}
