// This file is generated by scripts/generateCheckEntityTypes.ts
import { Spreadsheet } from '../../../../entities/Spreadsheet'
import { checkEntityTypeSpreadsheet } from '../single/checkEntityTypeSpreadsheet'

export const checkEntityTypeSpreadsheetList = (entity: unknown): entity is Spreadsheet[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeSpreadsheet(el)) {
      return false
    }
  }

  return true
}
