// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanClick } from '../../../../entities/ActionPlanClick'
import { checkEntityTypeActionPlanClick } from '../single/checkEntityTypeActionPlanClick'

export const checkEntityTypeActionPlanClickList = (entity: unknown): entity is ActionPlanClick[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanClick(el)) {
      return false
    }
  }

  return true
}
