// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultCreateSpreadsheet } from '../../../../entities/ActionResultCreateSpreadsheet'
import { checkEntityTypeActionResultCreateSpreadsheet } from '../single/checkEntityTypeActionResultCreateSpreadsheet'

export const checkEntityTypeActionResultCreateSpreadsheetList = (entity: unknown): entity is ActionResultCreateSpreadsheet[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultCreateSpreadsheet(el)) {
      return false
    }
  }

  return true
}
