// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultObserveWebPage } from '../../../../entities/ActionResultObserveWebPage'
import { checkEntityTypeActionResultObserveWebPage } from '../single/checkEntityTypeActionResultObserveWebPage'

export const checkEntityTypeActionResultObserveWebPageList = (entity: unknown): entity is ActionResultObserveWebPage[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultObserveWebPage(el)) {
      return false
    }
  }

  return true
}
