// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanAppendSheetToSpreadsheet } from '../../../../entities/ActionPlanAppendSheetToSpreadsheet'
import { checkEntityTypeActionPlanAppendSheetToSpreadsheet } from '../single/checkEntityTypeActionPlanAppendSheetToSpreadsheet'

export const checkEntityTypeActionPlanAppendSheetToSpreadsheetList = (entity: unknown): entity is ActionPlanAppendSheetToSpreadsheet[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanAppendSheetToSpreadsheet(el)) {
      return false
    }
  }

  return true
}
