// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultCollectData } from '../../../../entities/ActionResultCollectData'
import { checkEntityTypeActionResultCollectData } from '../single/checkEntityTypeActionResultCollectData'

export const checkEntityTypeActionResultCollectDataList = (entity: unknown): entity is ActionResultCollectData[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultCollectData(el)) {
      return false
    }
  }

  return true
}
