// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionResultClick } from '../ActionResultClick'
// Import Referred entities

// Import Sub type entities

export type ActionResultClickWithAssociation = ActionResultClick & {
  // Unique Referred entities
  // Non-unique Referred entities
}
