// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionResultCollectData } from '../ActionResultCollectData'
// Import Referred entities

// Import Sub type entities

export type ActionResultCollectDataWithAssociation = ActionResultCollectData & {
  // Unique Referred entities
  // Non-unique Referred entities
}
