// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanReportResult } from '../ActionPlanReportResult'
// Import Referred entities

// Import Sub type entities

export type ActionPlanReportResultWithAssociation = ActionPlanReportResult & {
  // Unique Referred entities
  // Non-unique Referred entities
}
