// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionResult } from '../ActionResult'
// Import Referred entities

// Import Sub type entities
import { ActionResultAppendSheetToSpreadsheetWithAssociation } from './ActionResultAppendSheetToSpreadsheetWithAssociation'
import { ActionResultClickWithAssociation } from './ActionResultClickWithAssociation'
import { ActionResultCollectDataWithAssociation } from './ActionResultCollectDataWithAssociation'
import { ActionResultCreateSpreadsheetWithAssociation } from './ActionResultCreateSpreadsheetWithAssociation'
import { ActionResultObserveWebPageWithAssociation } from './ActionResultObserveWebPageWithAssociation'
import { ActionResultReportResultWithAssociation } from './ActionResultReportResultWithAssociation'

export type ActionResultWithAssociation = ActionResult & {
  // Unique Referred entities
  // Non-unique Referred entities
} & // Sub type entities
  (| ActionResultAppendSheetToSpreadsheetWithAssociation
    | ActionResultClickWithAssociation
    | ActionResultCollectDataWithAssociation
    | ActionResultCreateSpreadsheetWithAssociation
    | ActionResultObserveWebPageWithAssociation
    | ActionResultReportResultWithAssociation
  )
