// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanCollectData } from '../ActionPlanCollectData'
// Import Referred entities

// Import Sub type entities

export type ActionPlanCollectDataWithAssociation = ActionPlanCollectData & {
  // Unique Referred entities
  // Non-unique Referred entities
}
