// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanAppendSheetToSpreadsheet } from '../ActionPlanAppendSheetToSpreadsheet'
// Import Referred entities

// Import Sub type entities

export type ActionPlanAppendSheetToSpreadsheetWithAssociation = ActionPlanAppendSheetToSpreadsheet & {
  // Unique Referred entities
  // Non-unique Referred entities
}
