// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanCollectData } from '../ActionPlanCollectData'
// Referrencing entities

// Sub type entities

export type ActionPlanCollectDataWithAssociation = ActionPlanCollectData & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
