// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanClick } from '../ActionPlanClick'
// Import Referred entities

// Import Sub type entities

export type ActionPlanClickWithAssociation = ActionPlanClick & {
  // Unique Referred entities
  // Non-unique Referred entities
}
