// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanClick } from '../ActionPlanClick'
// Referrencing entities

// Sub type entities

export type ActionPlanClickWithAssociation = ActionPlanClick & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
