// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanCreateSpreadsheet } from '../ActionPlanCreateSpreadsheet'
// Referrencing entities

// Sub type entities

export type ActionPlanCreateSpreadsheetWithAssociation = ActionPlanCreateSpreadsheet & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
