// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionResultAppendSheetToSpreadsheet } from '../ActionResultAppendSheetToSpreadsheet'
// Import Referred entities

// Import Sub type entities

export type ActionResultAppendSheetToSpreadsheetWithAssociation = ActionResultAppendSheetToSpreadsheet & {
  // Unique Referred entities
  // Non-unique Referred entities
}
