// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionResultReportResult } from '../ActionResultReportResult'
// Import Referred entities

// Import Sub type entities

export type ActionResultReportResultWithAssociation = ActionResultReportResult & {
  // Unique Referred entities
  // Non-unique Referred entities
}
