// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanObserveWebPage } from '../ActionPlanObserveWebPage'
// Referrencing entities

// Sub type entities

export type ActionPlanObserveWebPageWithAssociation = ActionPlanObserveWebPage & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
