// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlan } from '../ActionPlan'
// Referrencing entities

// Sub type entities
import { ActionPlanAppendSheetToSpreadsheetWithAssociation } from './ActionPlanAppendSheetToSpreadsheetWithAssociation'
import { ActionPlanClickWithAssociation } from './ActionPlanClickWithAssociation'
import { ActionPlanCollectDataWithAssociation } from './ActionPlanCollectDataWithAssociation'
import { ActionPlanCreateSpreadsheetWithAssociation } from './ActionPlanCreateSpreadsheetWithAssociation'
import { ActionPlanObserveWebPageWithAssociation } from './ActionPlanObserveWebPageWithAssociation'

export type ActionPlanWithAssociation = ActionPlan & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
} & // Sub type entities
  (| ActionPlanAppendSheetToSpreadsheetWithAssociation
    | ActionPlanClickWithAssociation
    | ActionPlanCollectDataWithAssociation
    | ActionPlanCreateSpreadsheetWithAssociation
    | ActionPlanObserveWebPageWithAssociation
  )
