// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionResultCreateSpreadsheet } from '../ActionResultCreateSpreadsheet'
// Import Referred entities

// Import Sub type entities

export type ActionResultCreateSpreadsheetWithAssociation = ActionResultCreateSpreadsheet & {
  // Unique Referred entities
  // Non-unique Referred entities
}
