// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanCreateSpreadsheet } from '../ActionPlanCreateSpreadsheet'
// Import Referred entities

// Import Sub type entities

export type ActionPlanCreateSpreadsheetWithAssociation = ActionPlanCreateSpreadsheet & {
  // Unique Referred entities
  // Non-unique Referred entities
}
