// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanObserveWebPage } from '../ActionPlanObserveWebPage'
// Import Referred entities

// Import Sub type entities

export type ActionPlanObserveWebPageWithAssociation = ActionPlanObserveWebPage & {
  // Unique Referred entities
  // Non-unique Referred entities
}
