// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionResultObserveWebPage } from '../ActionResultObserveWebPage'
// Import Referred entities

// Import Sub type entities

export type ActionResultObserveWebPageWithAssociation = ActionResultObserveWebPage & {
  // Unique Referred entities
  // Non-unique Referred entities
}
