// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { ActionPlanAppendSheetToSpreadsheet } from '../ActionPlanAppendSheetToSpreadsheet'
// Referrencing entities

// Sub type entities

export type ActionPlanAppendSheetToSpreadsheetWithAssociation = ActionPlanAppendSheetToSpreadsheet & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
