// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { CollectedData } from '../CollectedData'
// Referrencing entities

// Sub type entities

export type CollectedDataWithAssociation = CollectedData & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
