// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { SpreadsheetSheet } from '../SpreadsheetSheet'
// Import Referred entities

// Import Sub type entities

export type SpreadsheetSheetWithAssociation = SpreadsheetSheet & {
  // Unique Referred entities
  // Non-unique Referred entities
}
