// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { Spreadsheet } from '../Spreadsheet'
// Referrencing entities
import { SpreadsheetSheetWithAssociation } from './SpreadsheetSheetWithAssociation'
// Sub type entities

export type SpreadsheetWithAssociation = Spreadsheet & {
  // Unique Referrencing entities

  // Non-unique Referrencing entities
  spreadsheetSheets: SpreadsheetSheetWithAssociation[]
}
