// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { Spreadsheet } from '../Spreadsheet'
// Import Referred entities
import { SpreadsheetSheetWithAssociation } from './SpreadsheetSheetWithAssociation'
// Import Sub type entities

export type SpreadsheetWithAssociation = Spreadsheet & {
  // Unique Referred entities

  // Non-unique Referred entities
  spreadsheetSheets: SpreadsheetSheetWithAssociation[]
}
