// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { SpreadsheetSheet } from '../SpreadsheetSheet'
// Referrencing entities

// Sub type entities

export type SpreadsheetSheetWithAssociation = SpreadsheetSheet & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
