// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { UserRequest } from '../UserRequest'
// Referrencing entities
import { ActionPlanWithAssociation } from './ActionPlanWithAssociation'
// Sub type entities

export type UserRequestWithAssociation = UserRequest & {
  // Unique Referrencing entities

  // Non-unique Referrencing entities
  actionPlans: ActionPlanWithAssociation[]
}
