// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { UserRequest } from '../UserRequest'
// Import Referred entities
import { ActionPlanWithAssociation } from './ActionPlanWithAssociation'
// Import Sub type entities

export type UserRequestWithAssociation = UserRequest & {
  // Unique Referred entities

  // Non-unique Referred entities
  actionPlans: ActionPlanWithAssociation[]
}
