// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { WebPageElement } from '../WebPageElement'
// Referrencing entities

// Sub type entities
import { WebPageElementPageLinkWithAssociation } from './WebPageElementPageLinkWithAssociation'
import { WebPageElementTextWithAssociation } from './WebPageElementTextWithAssociation'

export type WebPageElementWithAssociation = WebPageElement & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
} & // Sub type entities
  (WebPageElementPageLinkWithAssociation | WebPageElementTextWithAssociation)
