// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { WebPageElementText } from '../WebPageElementText'
// Referrencing entities

// Sub type entities

export type WebPageElementTextWithAssociation = WebPageElementText & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
