// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { WebPage } from '../WebPage'
// Import Referred entities
import { WebPageElementWithAssociation } from './WebPageElementWithAssociation'
// Import Sub type entities

export type WebPageWithAssociation = WebPage & {
  // Unique Referred entities

  // Non-unique Referred entities
  webPageElements: WebPageElementWithAssociation[]
}
