// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { WebPage } from '../WebPage'
// Referrencing entities
import { WebPageElementWithAssociation } from './WebPageElementWithAssociation'
// Sub type entities

export type WebPageWithAssociation = WebPage & {
  // Unique Referrencing entities

  // Non-unique Referrencing entities
  webPageElements: WebPageElementWithAssociation[]
}
