// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { WebPageElementPageLink } from '../WebPageElementPageLink'
// Import Referred entities

// Import Sub type entities

export type WebPageElementPageLinkWithAssociation = WebPageElementPageLink & {
  // Unique Referred entities
  // Non-unique Referred entities
}
