// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { WebPageElement } from '../WebPageElement'
// Import Referred entities

// Import Sub type entities
import { WebPageElementPageLinkWithAssociation } from './WebPageElementPageLinkWithAssociation'
import { WebPageElementTextWithAssociation } from './WebPageElementTextWithAssociation'

export type WebPageElementWithAssociation = WebPageElement & {
  // Unique Referred entities
  // Non-unique Referred entities
} & // Sub type entities
  (WebPageElementPageLinkWithAssociation | WebPageElementTextWithAssociation)
