// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { WebPageElementText } from '../WebPageElementText'
// Import Referred entities

// Import Sub type entities

export type WebPageElementTextWithAssociation = WebPageElementText & {
  // Unique Referred entities
  // Non-unique Referred entities
}
