// This file is generated by scripts/generateEntityTypeWithAssociations.ts
import { WebPageElementPageLink } from '../WebPageElementPageLink'
// Referrencing entities

// Sub type entities

export type WebPageElementPageLinkWithAssociation = WebPageElementPageLink & {
  // Unique Referrencing entities
  // Non-unique Referrencing entities
}
