// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultClick } from '../../../../entities/ActionResultClick'

export const checkEntityTypeActionResultClick = (entity: unknown): entity is ActionResultClick => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('actionResultId' in entity) ||
    typeof entity.actionResultId !== 'string' ||
    !('type' in entity) ||
    !(entity.type === 'click') ||
    !('result' in entity) ||
    !(entity.result === 'done')
  ) {
    // console.log(`[checkEntityTypeActionResultClick] entity is not ActionResultClick: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
