// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageElementText } from '../../../../entities/WebPageElementText'

export const checkEntityTypeWebPageElementText = (entity: unknown): entity is WebPageElementText => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('webPageElementId' in entity) ||
    typeof entity.webPageElementId !== 'string' ||
    !('type' in entity) ||
    !(entity.type === 'text') ||
    !('text' in entity) ||
    typeof entity.text !== 'string'
  ) {
    // console.log(`[checkEntityTypeWebPageElementText] entity is not WebPageElementText: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
