// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultAppendSheetToSpreadsheet } from '../../../../entities/ActionResultAppendSheetToSpreadsheet'

export const checkEntityTypeActionResultAppendSheetToSpreadsheet = (entity: unknown): entity is ActionResultAppendSheetToSpreadsheet => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('actionResultId' in entity) ||
    typeof entity.actionResultId !== 'string' ||
    !('type' in entity) ||
    !(entity.type === 'appendSheetToSpreadsheet') ||
    !('spreadsheetId' in entity) ||
    typeof entity.spreadsheetId !== 'string' ||
    !('sheetNumber' in entity) ||
    typeof entity.sheetNumber !== 'number' ||
    !('collectedDataId' in entity) ||
    typeof entity.collectedDataId !== 'string'
  ) {
    // console.log(`[checkEntityTypeActionResultAppendSheetToSpreadsheet] entity is not ActionResultAppendSheetToSpreadsheet: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
