// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanAppendSheetToSpreadsheet } from '../../../../entities/ActionPlanAppendSheetToSpreadsheet'

export const checkEntityTypeActionPlanAppendSheetToSpreadsheet = (entity: unknown): entity is ActionPlanAppendSheetToSpreadsheet => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('actionPlanId' in entity) ||
    typeof entity.actionPlanId !== 'string' ||
    !('type' in entity) ||
    !(entity.type === 'appendSheetToSpreadsheet') ||
    !('parentSpreadsheetName' in entity) ||
    typeof entity.parentSpreadsheetName !== 'string' ||
    !('sheetName' in entity) ||
    typeof entity.sheetName !== 'string' ||
    !('sheetDescription' in entity) ||
    typeof entity.sheetDescription !== 'string' ||
    !('collectedDataName' in entity) ||
    typeof entity.collectedDataName !== 'string'
  ) {
    // console.log(`[checkEntityTypeActionPlanAppendSheetToSpreadsheet] entity is not ActionPlanAppendSheetToSpreadsheet: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
