// This file is generated by scripts/generateCheckEntityTypes.ts
import { CollectedData } from '../../../../entities/CollectedData'

export const checkEntityTypeCollectedData = (entity: unknown): entity is CollectedData => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('id' in entity) ||
    typeof entity.id !== 'string' ||
    !('name' in entity) ||
    typeof entity.name !== 'string' ||
    !('webPageUrl' in entity) ||
    typeof entity.webPageUrl !== 'string' ||
    !('description' in entity) ||
    typeof entity.description !== 'string'
  ) {
    // console.log(`[checkEntityTypeCollectedData] entity is not CollectedData: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
