// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanCollectData } from '../../../../entities/ActionPlanCollectData'

export const checkEntityTypeActionPlanCollectData = (entity: unknown): entity is ActionPlanCollectData => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('actionPlanId' in entity) ||
    typeof entity.actionPlanId !== 'string' ||
    !('type' in entity) ||
    !(entity.type === 'collectData') ||
    !('name' in entity) ||
    typeof entity.name !== 'string' ||
    !('url' in entity) ||
    typeof entity.url !== 'string' ||
    !('description' in entity) ||
    typeof entity.description !== 'string'
  ) {
    // console.log(`[checkEntityTypeActionPlanCollectData] entity is not ActionPlanCollectData: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
