// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultCollectData } from '../../../../entities/ActionResultCollectData'

export const checkEntityTypeActionResultCollectData = (entity: unknown): entity is ActionResultCollectData => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('actionResultId' in entity) ||
    typeof entity.actionResultId !== 'string' ||
    !('type' in entity) ||
    !(entity.type === 'collectData') ||
    !('collectedDataId' in entity) ||
    typeof entity.collectedDataId !== 'string'
  ) {
    // console.log(`[checkEntityTypeActionResultCollectData] entity is not ActionResultCollectData: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
