// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultObserveWebPage } from '../../../../entities/ActionResultObserveWebPage'

export const checkEntityTypeActionResultObserveWebPage = (entity: unknown): entity is ActionResultObserveWebPage => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('actionResultId' in entity) ||
    typeof entity.actionResultId !== 'string' ||
    !('type' in entity) ||
    !(entity.type === 'observeWebPage') ||
    !('result' in entity) ||
    !(entity.result === 'done')
  ) {
    // console.log(`[checkEntityTypeActionResultObserveWebPage] entity is not ActionResultObserveWebPage: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
