// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanReportResult } from '../../../../entities/ActionPlanReportResult'

export const checkEntityTypeActionPlanReportResult = (entity: unknown): entity is ActionPlanReportResult => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('actionPlanId' in entity) ||
    typeof entity.actionPlanId !== 'string' ||
    !('type' in entity) ||
    !(entity.type === 'reportResult') ||
    !('message' in entity) ||
    typeof entity.message !== 'string'
  ) {
    // console.log(`[checkEntityTypeActionPlanReportResult] entity is not ActionPlanReportResult: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
