// This file is generated by scripts/generateCheckEntityTypes.ts
import { Spreadsheet } from '../../../../entities/Spreadsheet'

export const checkEntityTypeSpreadsheet = (entity: unknown): entity is Spreadsheet => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('id' in entity) ||
    typeof entity.id !== 'string' ||
    !('name' in entity) ||
    typeof entity.name !== 'string' ||
    !('description' in entity) ||
    typeof entity.description !== 'string'
  ) {
    // console.log(`[checkEntityTypeSpreadsheet] entity is not Spreadsheet: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
