// This file is generated by scripts/generateCheckEntityTypes.ts
import { SpreadsheetSheet } from '../../../../entities/SpreadsheetSheet'

export const checkEntityTypeSpreadsheetSheet = (entity: unknown): entity is SpreadsheetSheet => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (
    !('id' in entity) ||
    typeof entity.id !== 'string' ||
    !('spreadsheetId' in entity) ||
    typeof entity.spreadsheetId !== 'string' ||
    !('collectedDataId' in entity) ||
    (entity.collectedDataId !== null && typeof entity.collectedDataId !== 'string') ||
    !('sheetNumber' in entity) ||
    typeof entity.sheetNumber !== 'number' ||
    !('name' in entity) ||
    typeof entity.name !== 'string' ||
    !('description' in entity) ||
    typeof entity.description !== 'string'
  ) {
    // console.log(`[checkEntityTypeSpreadsheetSheet] entity is not SpreadsheetSheet: ${JSON.stringify(entity)}`)
    return false
  }

  return true
}
