// This file is generated by scripts/generateFormatInstructions.ts
export const actionPlanCreateSpreadsheetFormatInstruction = (spreadsheetName: string, spreadsheetDescription: string): string => {
  return `{
      "type": 'createSpreadsheet',
      "spreadsheetName": string:${spreadsheetName},
      "spreadsheetDescription": string:${spreadsheetDescription}
    }`
}
