// This file is generated by scripts/generateFormatInstructions.ts
export const actionResultClickFormatInstruction = (): string => {
  return `{
      "type": 'click',
      "result": 'done'
    }`
}
