// This file is generated by scripts/generateFormatInstructions.ts
export const actionResultAppendSheetToSpreadsheetFormatInstruction = (spreadsheetId: string, sheetNumber: string, collectedDataId: string): string => {
  return `{
      "type": 'appendSheetToSpreadsheet',
      "spreadsheetId": string:${spreadsheetId},
      "sheetNumber": number:${sheetNumber},
      "collectedDataId": string:${collectedDataId}
    }`
}
