// This file is generated by scripts/generateFormatInstructions.ts
export const actionResultReportResultFormatInstruction = (message: string): string => {
  return `{
      "type": 'reportResult',
      "message": string:${message}
    }`
}
