// This file is generated by scripts/generateFormatInstructions.ts
export const actionPlanCollectDataFormatInstruction = (collectedDataName: string, webPageUrl: string, whatToCollect: string): string => {
  return `{
      "type": 'collectData',
      "collectedDataName": string:${collectedDataName},
      "webPageUrl": string:${webPageUrl},
      "whatToCollect": string:${whatToCollect}
    }`
}
