// This file is generated by scripts/generateFormatInstructions.ts
export const actionResultCollectDataFormatInstruction = (collectedDataId: string): string => {
  return `{
      "type": 'collectData',
      "collectedDataId": string:${collectedDataId}
    }`
}
