// This file is generated by scripts/generateFormatInstructions.ts
export const actionPlanFormatInstruction = (): string => {
  return `{
      "type": 'click' | 'observeWebPage' | 'collectData' | 'createSpreadsheet' | 'appendSheetToSpreadsheet' | 'reportResult'
    }`
}
