// This file is generated by scripts/generateFormatInstructions.ts
export const actionPlanAppendSheetToSpreadsheetFormatInstruction = (
  parentSpreadsheetName: string,
  sheetName: string,
  sheetDescription: string,
  collectedDataName: string,
): string => {
  return `{
      "type": 'appendSheetToSpreadsheet',
      "parentSpreadsheetName": string:${parentSpreadsheetName},
      "sheetName": string:${sheetName},
      "sheetDescription": string:${sheetDescription},
      "collectedDataName": string:${collectedDataName}
    }`
}
