// This file is generated by scripts/generateFormatInstructions.ts
export const actionPlanObserveWebPageFormatInstruction = (url: string): string => {
  return `{
      "type": 'observeWebPage',
      "url": string:${url}
    }`
}
