// This file is generated by scripts/generateFormatInstructions.ts
export const actionResultObserveWebPageFormatInstruction = (): string => {
  return `{
      "type": 'observeWebPage',
      "result": 'done'
    }`
}
