// This file is generated by scripts/generateFormatInstructions.ts
export const userRequestFormatInstruction = (url: string, prompt: string, requestedAt: string): string => {
  return `{
      "url": string:${url},
      "prompt": string:${prompt},
      "requestedAt": string:${requestedAt}
    }`
}
