// This file is generated by scripts/generateFormatInstructions.ts
export const webPageElementPageLinkFormatInstruction = (text: string, url: string): string => {
  return `{
      "type": 'pageLink',
      "text": string:${text},
      "url": string:${url}
    }`
}
