// This file is generated by scripts/generateFormatInstructions.ts
export const webPageFormatInstruction = (url: string, width: string, height: string): string => {
  return `{
      "url": string:${url},
      "width": number:${width},
      "height": number:${height}
    }`
}
