// This file is generated by scripts/generateFormatInstructions.ts
export const webPageElementTextFormatInstruction = (text: string): string => {
  return `{
      "type": 'text',
      "text": string:${text}
    }`
}
