// This file is generated by scripts/generateInterfaceRepositories.ts
import { ActionPlan } from '../../../entities/ActionPlan'
import { ActionPlanObserveWebPage } from '../../../entities/ActionPlanObserveWebPage'
import { PromisedResult, UnknownRuntimeError, AlreadyExistsError, NotFoundError } from '../../../../_shared/error'

export interface ActionPlanObserveWebPageRepository {
  issueId: () => PromisedResult<string, UnknownRuntimeError>
  getAll: () => PromisedResult<ActionPlanObserveWebPage[], UnknownRuntimeError>
  getRelevant: (text: string, limit: number) => PromisedResult<ActionPlanObserveWebPage[], UnknownRuntimeError>
  create: (entity: ActionPlanObserveWebPage) => PromisedResult<ActionPlanObserveWebPage, UnknownRuntimeError | AlreadyExistsError>
  update: (entity: ActionPlanObserveWebPage) => PromisedResult<ActionPlanObserveWebPage, UnknownRuntimeError | NotFoundError>
  delete: (id: string) => PromisedResult<void, UnknownRuntimeError | NotFoundError>
  getByActionPlanId: (ActionPlanId: ActionPlan['id']) => PromisedResult<ActionPlanObserveWebPage | null, UnknownRuntimeError>
}
