// This file is generated by scripts/generateInterfaceRepositories.ts
import { ActionPlan } from '../../../entities/ActionPlan'
import { ActionPlanAppendSheetToSpreadsheet } from '../../../entities/ActionPlanAppendSheetToSpreadsheet'
import { PromisedResult, UnknownRuntimeError, AlreadyExistsError, NotFoundError } from '../../../../_shared/error'

export interface ActionPlanAppendSheetToSpreadsheetRepository {
  issueId: () => PromisedResult<string, UnknownRuntimeError>
  getAll: () => PromisedResult<ActionPlanAppendSheetToSpreadsheet[], UnknownRuntimeError>
  getRelevant: (text: string, limit: number) => PromisedResult<ActionPlanAppendSheetToSpreadsheet[], UnknownRuntimeError>
  create: (entity: ActionPlanAppendSheetToSpreadsheet) => PromisedResult<ActionPlanAppendSheetToSpreadsheet, UnknownRuntimeError | AlreadyExistsError>
  update: (entity: ActionPlanAppendSheetToSpreadsheet) => PromisedResult<ActionPlanAppendSheetToSpreadsheet, UnknownRuntimeError | NotFoundError>
  delete: (id: string) => PromisedResult<void, UnknownRuntimeError | NotFoundError>
  getByActionPlanId: (ActionPlanId: ActionPlan['id']) => PromisedResult<ActionPlanAppendSheetToSpreadsheet | null, UnknownRuntimeError>
}
