// This file is generated by scripts/generateInterfaceRepositories.ts
import { CollectedData } from '../../../entities/CollectedData'
import { PromisedResult, UnknownRuntimeError } from '../../../../_shared/error'

export interface CollectedDataRepository {
  getAll: () => PromisedResult<CollectedData[], UnknownRuntimeError>
  getRelevant: (text: string, limit: number) => PromisedResult<CollectedData[], UnknownRuntimeError>
  create: (entity: CollectedData) => PromisedResult<CollectedData, UnknownRuntimeError>
  update: (entity: CollectedData) => PromisedResult<CollectedData, UnknownRuntimeError>
  delete: (id: string) => PromisedResult<void, UnknownRuntimeError>
  getById: (id: string) => PromisedResult<CollectedData | null, UnknownRuntimeError>
}
