// This file is generated by scripts/generateInterfaceRepositories.ts
import { WebPageElement } from '../../../entities/WebPageElement'
import { WebPageElementText } from '../../../entities/WebPageElementText'
import { PromisedResult, UnknownRuntimeError } from '../../../../_shared/error'

export interface WebPageElementTextRepository {
  getAll: () => PromisedResult<WebPageElementText[], UnknownRuntimeError>
  getRelevant: (text: string, limit: number) => PromisedResult<WebPageElementText[], UnknownRuntimeError>
  create: (entity: WebPageElementText) => PromisedResult<WebPageElementText, UnknownRuntimeError>
  update: (entity: WebPageElementText) => PromisedResult<WebPageElementText, UnknownRuntimeError>
  delete: (id: string) => PromisedResult<void, UnknownRuntimeError>
  getByWebPageElementId: (WebPageElementId: WebPageElement['id']) => PromisedResult<WebPageElementText | null, UnknownRuntimeError>
}
