// This file is generated by scripts/generateInterfaceRepositories.ts
import { WebPage } from '../../../entities/WebPage'
import { WebPageElement } from '../../../entities/WebPageElement'
import { PromisedResult, UnknownRuntimeError } from '../../../../_shared/error'

export interface WebPageElementRepository {
  getAll: () => PromisedResult<WebPageElement[], UnknownRuntimeError>
  getRelevant: (text: string, limit: number) => PromisedResult<WebPageElement[], UnknownRuntimeError>
  create: (entity: WebPageElement) => PromisedResult<WebPageElement, UnknownRuntimeError>
  update: (entity: WebPageElement) => PromisedResult<WebPageElement, UnknownRuntimeError>
  delete: (id: string) => PromisedResult<void, UnknownRuntimeError>
  getById: (id: string) => PromisedResult<WebPageElement | null, UnknownRuntimeError>
  getAllByWebPageId: (WebPageId: WebPage['id']) => PromisedResult<WebPageElement[], UnknownRuntimeError>
}
