// This file is generated by scripts/generateInterfaceRepositories.ts
import { WebPage } from '../../../entities/WebPage'
import { PromisedResult, UnknownRuntimeError } from '../../../../_shared/error'

export interface WebPageRepository {
  getAll: () => PromisedResult<WebPage[], UnknownRuntimeError>
  getRelevant: (text: string, limit: number) => PromisedResult<WebPage[], UnknownRuntimeError>
  create: (entity: WebPage) => PromisedResult<WebPage, UnknownRuntimeError>
  update: (entity: WebPage) => PromisedResult<WebPage, UnknownRuntimeError>
  delete: (id: string) => PromisedResult<void, UnknownRuntimeError>
  getById: (id: string) => PromisedResult<WebPage | null, UnknownRuntimeError>
}
