// This file is generated by scripts/generateVectorDbRepositories.ts
import { WebPageElementText } from '../../../../domain/entities/WebPageElementText'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'web_page_element_text'
const isWebPageElementText = (entity: unknown): entity is WebPageElementText => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'webPageElementId' in entity &&
    typeof entity.webPageElementId === 'string' &&
    'type' in entity &&
    typeof entity.type === 'string' &&
    'text' in entity &&
    typeof entity.text === 'string'
  )
}

export class VectorDbWebPageElementTextRepository extends VectorDbRepository<'webPageElementId', WebPageElementText> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super('webPageElementId', qdrantCollectionName, isWebPageElementText, qdrantClient, openAiClient)
  }

  getByWebPageElementId = async (webPageElementId: string): PromisedResult<WebPageElementText | null, UnknownRuntimeError> =>
    this.getByPrimaryKey(webPageElementId)
}
