// This file is generated by scripts/generateVectorDbRepositories.ts
import { WebPageElementPageLink } from '../../../../domain/entities/WebPageElementPageLink'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'web_page_element_page_link'
const isWebPageElementPageLink = (entity: unknown): entity is WebPageElementPageLink => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'id' in entity &&
    typeof entity.id === 'string' &&
    'webPageElementId' in entity &&
    typeof entity.webPageElementId === 'string' &&
    'url' in entity &&
    typeof entity.url === 'string'
  )
}

export class VectorDbWebPageElementPageLinkRepository extends VectorDbRepository<WebPageElementPageLink> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super(qdrantCollectionName, isWebPageElementPageLink, qdrantClient, openAiClient)
  }

  getByWebPageElementId = async (webPageElementId: string): PromisedResult<WebPageElementPageLink | null, UnknownRuntimeError> => {
    try {
      const scrollResult = await this.qdrantClient.scroll(this.qdrantCollectionName)
      const entities = scrollResult.points
        .map((point) => {
          if (!point.payload) {
            console.error(`[VectorDbWebPageElementPageLinkRepository] getByWebPageElementId: point.payload is null. Ignored ${point.id}`)

            return null
          }

          return this.isEntityType(point.payload) ? point.payload : null
        })
        .filter((entity): entity is WebPageElementPageLink => !!entity && entity.webPageElementId === webPageElementId)

      return Ok(entities[0] ?? null)
    } catch (e) {
      console.error(`[VectorDbWebPageElementPageLinkRepository] getByWebPageElementId: ${JSON.stringify(e)}`)

      if (e instanceof Error) {
        return unknownRuntimeError(e.message)
      } else {
        return unknownRuntimeError(JSON.stringify(e))
      }
    }
  }
}
