// This file is generated by scripts/generateVectorDbRepositories.ts
import { ActionPlanCreateSpreadsheet } from '../../../../domain/entities/ActionPlanCreateSpreadsheet'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'action_plan_create_spreadsheet'
const isActionPlanCreateSpreadsheet = (entity: unknown): entity is ActionPlanCreateSpreadsheet => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'actionPlanId' in entity &&
    typeof entity.actionPlanId === 'string' &&
    'type' in entity &&
    typeof entity.type === 'string' &&
    'spreadsheetName' in entity &&
    typeof entity.spreadsheetName === 'string' &&
    'spreadsheetDescription' in entity &&
    typeof entity.spreadsheetDescription === 'string'
  )
}

export class VectorDbActionPlanCreateSpreadsheetRepository extends VectorDbRepository<'actionPlanId', ActionPlanCreateSpreadsheet> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super('actionPlanId', qdrantCollectionName, isActionPlanCreateSpreadsheet, qdrantClient, openAiClient)
  }

  getByActionPlanId = async (actionPlanId: string): PromisedResult<ActionPlanCreateSpreadsheet | null, UnknownRuntimeError> =>
    this.getByPrimaryKey(actionPlanId)
}
