// This file is generated by scripts/generateVectorDbRepositories.ts
import { UserRequest } from '../../../../domain/entities/UserRequest'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'user_request'
const isUserRequest = (entity: unknown): entity is UserRequest => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'id' in entity &&
    typeof entity.id === 'string' &&
    'url' in entity &&
    typeof entity.url === 'string' &&
    'prompt' in entity &&
    typeof entity.prompt === 'string'
  )
}

export class VectorDbUserRequestRepository extends VectorDbRepository<UserRequest> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super(qdrantCollectionName, isUserRequest, qdrantClient, openAiClient)
  }
}
