// This file is generated by scripts/generateVectorDbRepositories.ts
import { ActionPlanClick } from '../../../../domain/entities/ActionPlanClick'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'action_plan_click'
const isActionPlanClick = (entity: unknown): entity is ActionPlanClick => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'actionPlanId' in entity &&
    typeof entity.actionPlanId === 'string' &&
    'type' in entity &&
    typeof entity.type === 'string' &&
    'label' in entity &&
    typeof entity.label === 'string' &&
    'x' in entity &&
    typeof entity.x === 'number' &&
    'y' in entity &&
    typeof entity.y === 'number'
  )
}

export class VectorDbActionPlanClickRepository extends VectorDbRepository<'actionPlanId', ActionPlanClick> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super('actionPlanId', qdrantCollectionName, isActionPlanClick, qdrantClient, openAiClient)
  }

  getByActionPlanId = async (actionPlanId: string): PromisedResult<ActionPlanClick | null, UnknownRuntimeError> => this.getByPrimaryKey(actionPlanId)
}
