// This file is generated by scripts/generateVectorDbRepositories.ts
import { ActionResultAppendSheetToSpreadsheet } from '../../../../domain/entities/ActionResultAppendSheetToSpreadsheet'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'action_result_append_sheet_to_spreadsheet'
const isActionResultAppendSheetToSpreadsheet = (entity: unknown): entity is ActionResultAppendSheetToSpreadsheet => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'actionResultId' in entity &&
    typeof entity.actionResultId === 'string' &&
    'type' in entity &&
    typeof entity.type === 'string' &&
    'spreadsheetId' in entity &&
    typeof entity.spreadsheetId === 'string' &&
    'sheetNumber' in entity &&
    typeof entity.sheetNumber === 'number' &&
    'collectedDataId' in entity &&
    typeof entity.collectedDataId === 'string'
  )
}

export class VectorDbActionResultAppendSheetToSpreadsheetRepository extends VectorDbRepository<'actionResultId', ActionResultAppendSheetToSpreadsheet> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super('actionResultId', qdrantCollectionName, isActionResultAppendSheetToSpreadsheet, qdrantClient, openAiClient)
  }

  getByActionResultId = async (actionResultId: string): PromisedResult<ActionResultAppendSheetToSpreadsheet | null, UnknownRuntimeError> =>
    this.getByPrimaryKey(actionResultId)
}
