// This file is generated by scripts/generateVectorDbRepositories.ts
import { Spreadsheet } from '../../../../domain/entities/Spreadsheet'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'spreadsheet'
const isSpreadsheet = (entity: unknown): entity is Spreadsheet => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'id' in entity &&
    typeof entity.id === 'string' &&
    'name' in entity &&
    typeof entity.name === 'string' &&
    'description' in entity &&
    typeof entity.description === 'string'
  )
}

export class VectorDbSpreadsheetRepository extends VectorDbRepository<'id', Spreadsheet> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super('id', qdrantCollectionName, isSpreadsheet, qdrantClient, openAiClient)
  }

  getById = async (id: string): PromisedResult<Spreadsheet | null, UnknownRuntimeError> => this.getByPrimaryKey(id)
}
