// This file is generated by scripts/generateVectorDbRepositories.ts
import { CollectedData } from '../../../../domain/entities/CollectedData'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'collected_data'
const isCollectedData = (entity: unknown): entity is CollectedData => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'id' in entity &&
    typeof entity.id === 'string' &&
    'name' in entity &&
    typeof entity.name === 'string' &&
    'webPageUrl' in entity &&
    typeof entity.webPageUrl === 'string' &&
    'description' in entity &&
    typeof entity.description === 'string'
  )
}

export class VectorDbCollectedDataRepository extends VectorDbRepository<'id', CollectedData> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super('id', qdrantCollectionName, isCollectedData, qdrantClient, openAiClient)
  }

  getById = async (id: string): PromisedResult<CollectedData | null, UnknownRuntimeError> => this.getByPrimaryKey(id)
}
