// This file is generated by scripts/generateVectorDbRepositories.ts
import { ActionResultCreateSpreadsheet } from '../../../../domain/entities/ActionResultCreateSpreadsheet'
import { QdrantClient } from '../../../_shared/QdrantClient'
import { OpenAiClient } from '../../../_shared/OpenAiClient'
import { VectorDbRepository } from '../_shared/VectorDbRepository'
/* eslint-disable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */
import { PromisedResult, UnknownRuntimeError, unknownRuntimeError } from '../../../../_shared/error'
import { Ok } from '@sniptt/monads'
/* eslint-enable @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports-ts */

const qdrantCollectionName = 'action_result_create_spreadsheet'
const isActionResultCreateSpreadsheet = (entity: unknown): entity is ActionResultCreateSpreadsheet => {
  return (
    typeof entity === 'object' &&
    entity !== null &&
    'actionResultId' in entity &&
    typeof entity.actionResultId === 'string' &&
    'type' in entity &&
    typeof entity.type === 'string' &&
    'spreadsheetId' in entity &&
    typeof entity.spreadsheetId === 'string'
  )
}

export class VectorDbActionResultCreateSpreadsheetRepository extends VectorDbRepository<'actionResultId', ActionResultCreateSpreadsheet> {
  constructor(qdrantClient: QdrantClient, openAiClient: OpenAiClient) {
    super('actionResultId', qdrantCollectionName, isActionResultCreateSpreadsheet, qdrantClient, openAiClient)
  }

  getByActionResultId = async (actionResultId: string): PromisedResult<ActionResultCreateSpreadsheet | null, UnknownRuntimeError> =>
    this.getByPrimaryKey(actionResultId)
}
