// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultClickWithAssociation } from '../../../../entities/_gen/ActionResultClickWithAssociation'
import { checkEntityTypeActionResultClickWithAssociation } from '../withAssociation/checkEntityTypeActionResultClickWithAssociation'

export const checkEntityTypeActionResultClickWithAssociationList = (entity: unknown): entity is ActionResultClickWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultClickWithAssociation(el)) {
      return false
    }
  }

  return true
}
