// This file is generated by scripts/generateCheckEntityTypes.ts
import { UserRequestWithAssociation } from '../../../../entities/_gen/UserRequestWithAssociation'
import { checkEntityTypeUserRequestWithAssociation } from '../withAssociation/checkEntityTypeUserRequestWithAssociation'

export const checkEntityTypeUserRequestWithAssociationList = (entity: unknown): entity is UserRequestWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeUserRequestWithAssociation(el)) {
      return false
    }
  }

  return true
}
