// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageElementWithAssociation } from '../../../../entities/_gen/WebPageElementWithAssociation'
import { checkEntityTypeWebPageElementWithAssociation } from '../withAssociation/checkEntityTypeWebPageElementWithAssociation'

export const checkEntityTypeWebPageElementWithAssociationList = (entity: unknown): entity is WebPageElementWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeWebPageElementWithAssociation(el)) {
      return false
    }
  }

  return true
}
