// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanCollectDataWithAssociation } from '../../../../entities/_gen/ActionPlanCollectDataWithAssociation'
import { checkEntityTypeActionPlanCollectDataWithAssociation } from '../withAssociation/checkEntityTypeActionPlanCollectDataWithAssociation'

export const checkEntityTypeActionPlanCollectDataWithAssociationList = (entity: unknown): entity is ActionPlanCollectDataWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanCollectDataWithAssociation(el)) {
      return false
    }
  }

  return true
}
