// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanWithAssociation } from '../../../../entities/_gen/ActionPlanWithAssociation'
import { checkEntityTypeActionPlanWithAssociation } from '../withAssociation/checkEntityTypeActionPlanWithAssociation'

export const checkEntityTypeActionPlanWithAssociationList = (entity: unknown): entity is ActionPlanWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanWithAssociation(el)) {
      return false
    }
  }

  return true
}
