// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageElementPageLinkWithAssociation } from '../../../../entities/_gen/WebPageElementPageLinkWithAssociation'
import { checkEntityTypeWebPageElementPageLinkWithAssociation } from '../withAssociation/checkEntityTypeWebPageElementPageLinkWithAssociation'

export const checkEntityTypeWebPageElementPageLinkWithAssociationList = (entity: unknown): entity is WebPageElementPageLinkWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeWebPageElementPageLinkWithAssociation(el)) {
      return false
    }
  }

  return true
}
