// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanClickWithAssociation } from '../../../../entities/_gen/ActionPlanClickWithAssociation'
import { checkEntityTypeActionPlanClickWithAssociation } from '../withAssociation/checkEntityTypeActionPlanClickWithAssociation'

export const checkEntityTypeActionPlanClickWithAssociationList = (entity: unknown): entity is ActionPlanClickWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanClickWithAssociation(el)) {
      return false
    }
  }

  return true
}
