// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanAppendSheetToSpreadsheetWithAssociation } from '../../../../entities/_gen/ActionPlanAppendSheetToSpreadsheetWithAssociation'
import { checkEntityTypeActionPlanAppendSheetToSpreadsheetWithAssociation } from '../withAssociation/checkEntityTypeActionPlanAppendSheetToSpreadsheetWithAssociation'

export const checkEntityTypeActionPlanAppendSheetToSpreadsheetWithAssociationList = (
  entity: unknown,
): entity is ActionPlanAppendSheetToSpreadsheetWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanAppendSheetToSpreadsheetWithAssociation(el)) {
      return false
    }
  }

  return true
}
