// This file is generated by scripts/generateCheckEntityTypes.ts
import { SpreadsheetSheetWithAssociation } from '../../../../entities/_gen/SpreadsheetSheetWithAssociation'
import { checkEntityTypeSpreadsheetSheetWithAssociation } from '../withAssociation/checkEntityTypeSpreadsheetSheetWithAssociation'

export const checkEntityTypeSpreadsheetSheetWithAssociationList = (entity: unknown): entity is SpreadsheetSheetWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeSpreadsheetSheetWithAssociation(el)) {
      return false
    }
  }

  return true
}
