// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultAppendSheetToSpreadsheetWithAssociation } from '../../../../entities/_gen/ActionResultAppendSheetToSpreadsheetWithAssociation'
import { checkEntityTypeActionResultAppendSheetToSpreadsheetWithAssociation } from '../withAssociation/checkEntityTypeActionResultAppendSheetToSpreadsheetWithAssociation'

export const checkEntityTypeActionResultAppendSheetToSpreadsheetWithAssociationList = (
  entity: unknown,
): entity is ActionResultAppendSheetToSpreadsheetWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultAppendSheetToSpreadsheetWithAssociation(el)) {
      return false
    }
  }

  return true
}
