// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageElementTextWithAssociation } from '../../../../entities/_gen/WebPageElementTextWithAssociation'
import { checkEntityTypeWebPageElementTextWithAssociation } from '../withAssociation/checkEntityTypeWebPageElementTextWithAssociation'

export const checkEntityTypeWebPageElementTextWithAssociationList = (entity: unknown): entity is WebPageElementTextWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeWebPageElementTextWithAssociation(el)) {
      return false
    }
  }

  return true
}
