// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultReportResultWithAssociation } from '../../../../entities/_gen/ActionResultReportResultWithAssociation'
import { checkEntityTypeActionResultReportResultWithAssociation } from '../withAssociation/checkEntityTypeActionResultReportResultWithAssociation'

export const checkEntityTypeActionResultReportResultWithAssociationList = (entity: unknown): entity is ActionResultReportResultWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultReportResultWithAssociation(el)) {
      return false
    }
  }

  return true
}
