// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultCreateSpreadsheetWithAssociation } from '../../../../entities/_gen/ActionResultCreateSpreadsheetWithAssociation'
import { checkEntityTypeActionResultCreateSpreadsheetWithAssociation } from '../withAssociation/checkEntityTypeActionResultCreateSpreadsheetWithAssociation'

export const checkEntityTypeActionResultCreateSpreadsheetWithAssociationList = (entity: unknown): entity is ActionResultCreateSpreadsheetWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultCreateSpreadsheetWithAssociation(el)) {
      return false
    }
  }

  return true
}
