// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanCreateSpreadsheetWithAssociation } from '../../../../entities/_gen/ActionPlanCreateSpreadsheetWithAssociation'
import { checkEntityTypeActionPlanCreateSpreadsheetWithAssociation } from '../withAssociation/checkEntityTypeActionPlanCreateSpreadsheetWithAssociation'

export const checkEntityTypeActionPlanCreateSpreadsheetWithAssociationList = (entity: unknown): entity is ActionPlanCreateSpreadsheetWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionPlanCreateSpreadsheetWithAssociation(el)) {
      return false
    }
  }

  return true
}
