// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageWithAssociation } from '../../../../entities/_gen/WebPageWithAssociation'
import { checkEntityTypeWebPageWithAssociation } from '../withAssociation/checkEntityTypeWebPageWithAssociation'

export const checkEntityTypeWebPageWithAssociationList = (entity: unknown): entity is WebPageWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeWebPageWithAssociation(el)) {
      return false
    }
  }

  return true
}
