// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultObserveWebPageWithAssociation } from '../../../../entities/_gen/ActionResultObserveWebPageWithAssociation'
import { checkEntityTypeActionResultObserveWebPageWithAssociation } from '../withAssociation/checkEntityTypeActionResultObserveWebPageWithAssociation'

export const checkEntityTypeActionResultObserveWebPageWithAssociationList = (entity: unknown): entity is ActionResultObserveWebPageWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeActionResultObserveWebPageWithAssociation(el)) {
      return false
    }
  }

  return true
}
