// This file is generated by scripts/generateCheckEntityTypes.ts
import { CollectedDataWithAssociation } from '../../../../entities/_gen/CollectedDataWithAssociation'
import { checkEntityTypeCollectedDataWithAssociation } from '../withAssociation/checkEntityTypeCollectedDataWithAssociation'

export const checkEntityTypeCollectedDataWithAssociationList = (entity: unknown): entity is CollectedDataWithAssociation[] => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!Array.isArray(entity)) {
    return false
  }

  for (const el of entity) {
    if (!checkEntityTypeCollectedDataWithAssociation(el)) {
      return false
    }
  }

  return true
}
