// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultClickWithAssociation } from '../../../../entities/_gen/ActionResultClickWithAssociation'
import { checkEntityTypeActionResultClick } from '../single/checkEntityTypeActionResultClick'

export const checkEntityTypeActionResultClickWithAssociation = (entity: unknown): entity is ActionResultClickWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionResultClick(entity)) {
    return false
  }

  return true
}
