// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageElementWithAssociation } from '../../../../entities/_gen/WebPageElementWithAssociation'
import { checkEntityTypeWebPageElement } from '../single/checkEntityTypeWebPageElement'
import { checkEntityTypeWebPageElementPageLinkWithAssociation } from '../withAssociation/checkEntityTypeWebPageElementPageLinkWithAssociation'
import { checkEntityTypeWebPageElementTextWithAssociation } from '../withAssociation/checkEntityTypeWebPageElementTextWithAssociation'

export const checkEntityTypeWebPageElementWithAssociation = (entity: unknown): entity is WebPageElementWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeWebPageElement(entity)) {
    return false
  }

  if (!(checkEntityTypeWebPageElementPageLinkWithAssociation(entity) || checkEntityTypeWebPageElementTextWithAssociation(entity))) {
    return false
  }

  return true
}
