// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanClickWithAssociation } from '../../../../entities/_gen/ActionPlanClickWithAssociation'
import { checkEntityTypeActionPlanClick } from '../single/checkEntityTypeActionPlanClick'

export const checkEntityTypeActionPlanClickWithAssociation = (entity: unknown): entity is ActionPlanClickWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionPlanClick(entity)) {
    return false
  }

  return true
}
