// This file is generated by scripts/generateCheckEntityTypes.ts
import { UserRequestWithAssociation } from '../../../../entities/_gen/UserRequestWithAssociation'
import { checkEntityTypeUserRequest } from '../single/checkEntityTypeUserRequest'

export const checkEntityTypeUserRequestWithAssociation = (entity: unknown): entity is UserRequestWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeUserRequest(entity)) {
    return false
  }

  return true
}
