// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanCollectDataWithAssociation } from '../../../../entities/_gen/ActionPlanCollectDataWithAssociation'
import { checkEntityTypeActionPlanCollectData } from '../single/checkEntityTypeActionPlanCollectData'

export const checkEntityTypeActionPlanCollectDataWithAssociation = (entity: unknown): entity is ActionPlanCollectDataWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionPlanCollectData(entity)) {
    return false
  }

  return true
}
