// This file is generated by scripts/generateCheckEntityTypes.ts
import { SpreadsheetSheetWithAssociation } from '../../../../entities/_gen/SpreadsheetSheetWithAssociation'
import { checkEntityTypeSpreadsheetSheet } from '../single/checkEntityTypeSpreadsheetSheet'

export const checkEntityTypeSpreadsheetSheetWithAssociation = (entity: unknown): entity is SpreadsheetSheetWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeSpreadsheetSheet(entity)) {
    return false
  }

  return true
}
