// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultAppendSheetToSpreadsheetWithAssociation } from '../../../../entities/_gen/ActionResultAppendSheetToSpreadsheetWithAssociation'
import { checkEntityTypeActionResultAppendSheetToSpreadsheet } from '../single/checkEntityTypeActionResultAppendSheetToSpreadsheet'

export const checkEntityTypeActionResultAppendSheetToSpreadsheetWithAssociation = (
  entity: unknown,
): entity is ActionResultAppendSheetToSpreadsheetWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionResultAppendSheetToSpreadsheet(entity)) {
    return false
  }

  return true
}
