// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageElementPageLinkWithAssociation } from '../../../../entities/_gen/WebPageElementPageLinkWithAssociation'
import { checkEntityTypeWebPageElementPageLink } from '../single/checkEntityTypeWebPageElementPageLink'

export const checkEntityTypeWebPageElementPageLinkWithAssociation = (entity: unknown): entity is WebPageElementPageLinkWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeWebPageElementPageLink(entity)) {
    return false
  }

  return true
}
