// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanCreateSpreadsheetWithAssociation } from '../../../../entities/_gen/ActionPlanCreateSpreadsheetWithAssociation'
import { checkEntityTypeActionPlanCreateSpreadsheet } from '../single/checkEntityTypeActionPlanCreateSpreadsheet'

export const checkEntityTypeActionPlanCreateSpreadsheetWithAssociation = (entity: unknown): entity is ActionPlanCreateSpreadsheetWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionPlanCreateSpreadsheet(entity)) {
    return false
  }

  return true
}
