// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageWithAssociation } from '../../../../entities/_gen/WebPageWithAssociation'
import { checkEntityTypeWebPage } from '../single/checkEntityTypeWebPage'

export const checkEntityTypeWebPageWithAssociation = (entity: unknown): entity is WebPageWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeWebPage(entity)) {
    return false
  }

  return true
}
