// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionPlanReportResultWithAssociation } from '../../../../entities/_gen/ActionPlanReportResultWithAssociation'
import { checkEntityTypeActionPlanReportResult } from '../single/checkEntityTypeActionPlanReportResult'

export const checkEntityTypeActionPlanReportResultWithAssociation = (entity: unknown): entity is ActionPlanReportResultWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionPlanReportResult(entity)) {
    return false
  }

  return true
}
