// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultCollectDataWithAssociation } from '../../../../entities/_gen/ActionResultCollectDataWithAssociation'
import { checkEntityTypeActionResultCollectData } from '../single/checkEntityTypeActionResultCollectData'

export const checkEntityTypeActionResultCollectDataWithAssociation = (entity: unknown): entity is ActionResultCollectDataWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionResultCollectData(entity)) {
    return false
  }

  return true
}
