// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultReportResultWithAssociation } from '../../../../entities/_gen/ActionResultReportResultWithAssociation'
import { checkEntityTypeActionResultReportResult } from '../single/checkEntityTypeActionResultReportResult'

export const checkEntityTypeActionResultReportResultWithAssociation = (entity: unknown): entity is ActionResultReportResultWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionResultReportResult(entity)) {
    return false
  }

  return true
}
