// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultObserveWebPageWithAssociation } from '../../../../entities/_gen/ActionResultObserveWebPageWithAssociation'
import { checkEntityTypeActionResultObserveWebPage } from '../single/checkEntityTypeActionResultObserveWebPage'

export const checkEntityTypeActionResultObserveWebPageWithAssociation = (entity: unknown): entity is ActionResultObserveWebPageWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionResultObserveWebPage(entity)) {
    return false
  }

  return true
}
