// This file is generated by scripts/generateCheckEntityTypes.ts
import { WebPageElementTextWithAssociation } from '../../../../entities/_gen/WebPageElementTextWithAssociation'
import { checkEntityTypeWebPageElementText } from '../single/checkEntityTypeWebPageElementText'

export const checkEntityTypeWebPageElementTextWithAssociation = (entity: unknown): entity is WebPageElementTextWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeWebPageElementText(entity)) {
    return false
  }

  return true
}
