// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultWithAssociation } from '../../../../entities/_gen/ActionResultWithAssociation'
import { checkEntityTypeActionResult } from '../single/checkEntityTypeActionResult'
import { checkEntityTypeActionResultAppendSheetToSpreadsheetWithAssociation } from '../withAssociation/checkEntityTypeActionResultAppendSheetToSpreadsheetWithAssociation'
import { checkEntityTypeActionResultClickWithAssociation } from '../withAssociation/checkEntityTypeActionResultClickWithAssociation'
import { checkEntityTypeActionResultCollectDataWithAssociation } from '../withAssociation/checkEntityTypeActionResultCollectDataWithAssociation'
import { checkEntityTypeActionResultCreateSpreadsheetWithAssociation } from '../withAssociation/checkEntityTypeActionResultCreateSpreadsheetWithAssociation'
import { checkEntityTypeActionResultObserveWebPageWithAssociation } from '../withAssociation/checkEntityTypeActionResultObserveWebPageWithAssociation'
import { checkEntityTypeActionResultReportResultWithAssociation } from '../withAssociation/checkEntityTypeActionResultReportResultWithAssociation'

export const checkEntityTypeActionResultWithAssociation = (entity: unknown): entity is ActionResultWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionResult(entity)) {
    return false
  }

  if (
    !(
      checkEntityTypeActionResultAppendSheetToSpreadsheetWithAssociation(entity) ||
      checkEntityTypeActionResultClickWithAssociation(entity) ||
      checkEntityTypeActionResultCollectDataWithAssociation(entity) ||
      checkEntityTypeActionResultCreateSpreadsheetWithAssociation(entity) ||
      checkEntityTypeActionResultObserveWebPageWithAssociation(entity) ||
      checkEntityTypeActionResultReportResultWithAssociation(entity)
    )
  ) {
    return false
  }

  return true
}
