// This file is generated by scripts/generateCheckEntityTypes.ts
import { ActionResultCreateSpreadsheetWithAssociation } from '../../../../entities/_gen/ActionResultCreateSpreadsheetWithAssociation'
import { checkEntityTypeActionResultCreateSpreadsheet } from '../single/checkEntityTypeActionResultCreateSpreadsheet'

export const checkEntityTypeActionResultCreateSpreadsheetWithAssociation = (entity: unknown): entity is ActionResultCreateSpreadsheetWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeActionResultCreateSpreadsheet(entity)) {
    return false
  }

  return true
}
