// This file is generated by scripts/generateCheckEntityTypes.ts
import { SpreadsheetWithAssociation } from '../../../../entities/_gen/SpreadsheetWithAssociation'
import { checkEntityTypeSpreadsheet } from '../single/checkEntityTypeSpreadsheet'

export const checkEntityTypeSpreadsheetWithAssociation = (entity: unknown): entity is SpreadsheetWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeSpreadsheet(entity)) {
    return false
  }

  return true
}
