// This file is generated by scripts/generateCheckEntityTypes.ts
import { CollectedDataWithAssociation } from '../../../../entities/_gen/CollectedDataWithAssociation'
import { checkEntityTypeCollectedData } from '../single/checkEntityTypeCollectedData'

export const checkEntityTypeCollectedDataWithAssociation = (entity: unknown): entity is CollectedDataWithAssociation => {
  if (typeof entity !== 'object' || entity === null) {
    return false
  }

  if (!checkEntityTypeCollectedData(entity)) {
    return false
  }

  return true
}
